import Head from "next/head";

export default function Home() {
	return (
		<div>
			<Head>
				<title>N_Blog Post App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container max-w-screen-lg mx-auto flex flex-col justify-between items-center pt-40 h-screen">
				Main Page
			</main>
		</div>
	);
}
