const ActionTypes = {
	USER_SIGN_UP: "USER_SIGN_UP",
	USER_SIGN_IN: "USER_SIGN_IN",

	GET_ALL_POSTS: "GET_ALL_POSTS",
	GET_POST: "GET_POST",

	CREATE_POST: "CREATE_POST",

	GET_SINGLE_USER: "GET_SINGLE_USER",
	GET_ALL_USERS: "GET_ALL_USERS",
};

export default ActionTypes;
